# Generated by Django 2.0.3 on 2018-04-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image_quota',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='upload_quota',
            field=models.IntegerField(default=100),
        ),
    ]
