# Generated by Django 2.0.3 on 2018-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image_quota',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='member',
            name='upload_quota',
            field=models.IntegerField(default=4),
        ),
    ]
