# Generated by Django 2.0.3 on 2018-04-02 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=image.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Member')),
            ],
        ),
    ]
