# Generated by Django 2.0.3 on 2018-04-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_auto_20180424_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tags',
            new_name='tag',
        ),
    ]
