# Generated by Django 2.0.3 on 2018-04-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_auto_20180424_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.CharField(max_length=50),
        ),
    ]
