# Generated by Django 2.0.3 on 2018-04-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0011_auto_20180424_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
