# Generated by Django 2.0.3 on 2018-04-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_auto_20180426_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='download',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
