# Generated by Django 2.0.3 on 2018-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_auto_20180426_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
