# Generated by Django 2.0.3 on 2018-04-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0013_image_download_count'),
        ('image', '0014_remove_image_download'),
    ]

    operations = [
    ]
