# Generated by Django 2.0.3 on 2018-03-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default='imageX', on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
    ]
