# Generated by Django 2.0.3 on 2018-03-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20180322_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_name',
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Member'),
        ),
    ]
