# Generated by Django 2.0.3 on 2018-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20180322_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
