# Generated by Django 2.0.3 on 2018-03-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_member_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
    ]
