# Generated by Django 2.0.1 on 2018-03-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_image_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
    ]
