# Generated by Django 2.0.3 on 2018-03-22 14:43

from django.db import migrations, models
import search.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_image_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='media/no_image', upload_to=search.models.user_directory_path),
        ),
    ]
